# Generated by Django 2.0.7 on 2019-09-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFront', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='Num',
            new_name='PostNo',
        ),
    ]
