# Generated by Django 2.0.7 on 2019-09-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsFront', '0002_auto_20190909_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
